version: '3'

services:
  tagio-relay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - PUBLIC_IP=automatic
      - AUTH_SECRET=tagio_default_secret
    restart: unless-stopped 