services:
  - type: web
    name: tagio-relay-server
    env: rust
    buildCommand: cargo build --release --bin http_tunnel_server
    startCommand: PORT=10000 ./target/release/http_tunnel_server --port 10000
    region: frankfurt
    plan: starter
    healthCheckPath: /
    # The following envVars are used for configuration
    envVars:
      - key: AUTH_TOKEN
        sync: false # Set to false to allow custom values per environment
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 10000
      - key: SERVER_NAME
        value: tagio-server.onrender.com
    
    # Render automatically sets PORT=10000 for web services
    autoDeploy: true
    # Scaling settings (Pro+ plans only)
    scaling:
      minInstances: 1
      maxInstances: 1
    # Increased deployment timeout for slower builds
    initialDeployHook: echo "Starting TagIO HTTP Tunnel Server deployment"
    # HTTP tunnel server handles its own HTTP requests
    # No need for TCP proxy configuration
    tcpPorts:
      - port: 80
        name: tagio-http
        proxy:
          port: 10000
          protocol: http 