services:
  - type: web
    name: tagio-relay
    runtime: rust
    region: ohio
    plan: free
    branch: main
    buildCommand: cargo build --release --bin tagio_relay_server
    startCommand: ./target/release/tagio_relay_server
    envVars:
      - key: PUBLIC_IP
        value: automatic
      - key: RUST_LOG
        value: info
      - key: AUTH_SECRET
        value: tagio_default_secret # Change this for production use
    healthCheckPath: /health 