services:
  - type: web
    name: tagio-relay-server
    env: rust
    buildCommand: cargo build --release --bin tagio_relay_server
    startCommand: PORT=10000 ./target/release/tagio_relay_server --force_cloud_ip
    region: frankfurt
    plan: starter
    healthCheckPath: /
    # The following envVars are used for configuration
    envVars:
      - key: AUTH_TOKEN
        sync: false # Set to false to allow custom values per environment
      - key: RUST_LOG
        value: info
    
    # Render automatically sets PORT=10000 for web services
    # The server is internally bound to port 10000, but clients should connect on 443
    autoDeploy: true
    # Scaling settings (Pro+ plans only)
    scaling:
      minInstances: 1
      maxInstances: 1
    # Increased deployment timeout for slower builds
    initialDeployHook: echo "Starting TagIO Relay Server deployment"
    # Configure TCP proxy instead of HTTP proxy
    tcpPorts:
      - port: 443
        name: tagio
        proxy:
          port: 10000
          protocol: tcp 