services:
  - type: web
    name: tagio-relay-server
    env: rust
    plan: free # Change to starter/standard for production
    buildCommand: cargo build --release
    startCommand: ./target/release/tagio_relay_server
    envVars:
      - key: PORT
        value: 10000
      - key: PUBLIC_IP
        sync: false # Will be auto-detected, but can be manually set in dashboard
      - key: AUTH_SECRET
        sync: false # Add in dashboard for security
    healthCheckPath: / # Health check endpoint
    # Deployment settings
    autoDeploy: true
    # Scaling settings (Pro+ plans only)
    scaling:
      minInstances: 1
      maxInstances: 1
    # Increased deployment timeout for slower builds
    initialDeployHook: echo "Starting TagIO Relay Server deployment" 