services:
  - type: web
    name: tagio-relay-server
    env: rust
    buildCommand: cargo build --release --bin tagio_relay_server
    startCommand: PORT=10000 ./target/release/tagio_relay_server --force_cloud_ip
    region: frankfurt
    plan: starter
    healthCheckPath: /health
    # The following envVars are used for configuration
    envVars:
      - key: AUTH_TOKEN
        sync: false # Set to false to allow custom values per environment
      - key: RUST_LOG
        value: trace
      - key: PORT
        value: 10000
      - key: SERVER_NAME
        value: tagio-server.onrender.com
    
    # Render automatically sets PORT=10000 for web services
    # The server is internally bound to port 10000, but clients should connect on port 7568
    autoDeploy: true
    # Scaling settings (Pro+ plans only)
    scaling:
      minInstances: 1
      maxInstances: 1
    # Increased deployment timeout for slower builds
    initialDeployHook: echo "Starting TagIO Relay Server deployment"
    # Configure TCP proxy instead of HTTP proxy
    # Use port 7568 instead of standard ports 80/443 to avoid HTTP protocol enforcement
    tcpPorts:
      - port: 7568
        name: tagio-tcp
        proxy:
          port: 10000
          protocol: tcp 